# Install-DevMode.ps1
# Switch THIS machine to dev mode: AutoCAD loads the tools straight from the
# source tree, so edit -> OLOAD -> test works with no reinstall.
#
#   powershell -ExecutionPolicy Bypass -File Install-DevMode.ps1
#
# Reversible: to go back to the packaged copy (what teammates run), extract the
# release zip and run "Install Opal CAD Tools.bat". Re-run this script if you
# rename/move the source folders.

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Path   # opal-cad-installer
$auto = Split-Path -Parent $here                          # Automations
$dest = "$env:APPDATA\Autodesk\ApplicationPlugins\OpalTools.bundle"
$enc  = New-Object System.Text.UTF8Encoding($false)
$ver  = (Get-Content (Join-Path $here "VERSION") -Raw).Trim()   # single source of the version string

if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
New-Item -ItemType Directory "$dest\Contents" -Force | Out-Null

$xml = @"
<?xml version="1.0" encoding="utf-8"?>
<ApplicationPackage SchemaVersion="1.0" ProductCode="{7E9C1A40-2B6F-4D8E-9A11-0C0FA1000001}" Name="Opal CAD Tools (DEV)" Description="Opal CAD Tools - dev mode (loads from source)" AppVersion="$ver" Author="Adrian Hood">
  <CompanyDetails Name="Opal Energy" />
  <Components>
    <RuntimeRequirements OS="Win64" Platform="AutoCAD*" />
    <ComponentEntry AppName="OpalCADTools" Version="$ver" ModuleName="./Contents/bootstrap.lsp" AppType="LISP" LoadOnAutoCADStartup="True" />
  </Components>
</ApplicationPackage>
"@
[System.IO.File]::WriteAllText("$dest\PackageContents.xml", $xml, $enc)

$o = ($auto + "\opal-tools\").Replace('\','\\')
$l = ($auto + "\layer-kit\").Replace('\','\\')
$boot = @"
;; DEV bootstrap -- loads Opal CAD Tools from the SOURCE tree (not a copy).
;; Generated by Install-DevMode.ps1. Re-run that script if source paths change.
(vl-load-com)
(setq *o-suite-root* "$o")
(setq *lk-suite-root* "$l")
(setq *oload-quiet* T *lkload-quiet* T)
(defun _opal-str< (a b / i ca cb)
  (setq i 1)
  (while (and (<= i (strlen a)) (<= i (strlen b))
              (= (setq ca (ascii (substr a i 1))) (setq cb (ascii (substr b i 1)))))
    (setq i (1+ i)))
  (cond ((> i (strlen a)) (< (strlen a) (strlen b))) ((> i (strlen b)) nil) (T (< ca cb))))
(defun _opal-latest (folder / files best f)
  (setq files (vl-directory-files folder "*.lsp" 1) best nil)
  (foreach f files (if (or (not best) (_opal-str< best f)) (setq best f)))
  (if best (load (strcat folder best)) nil))
(_opal-latest (strcat *o-suite-root* "oload\\"))
(_opal-latest (strcat *lk-suite-root* "lkload\\"))
;; O-LOAD (v1.10+) loads the O-Suite AND then LayerKit, so one C:O-LOAD does both.
;; lkload is loaded above so LK-LOAD exists for manual use; O-LOAD owns the call.
(if (member "C:O-LOAD" (atoms-family 1 (list "C:O-LOAD")))  (C:O-LOAD))
(setq *oload-quiet* nil *lkload-quiet* nil)
(princ "\nOpal CAD Tools loaded in DEV mode (from source). Type O or OHELP.")
(princ)
"@
[System.IO.File]::WriteAllText("$dest\Contents\bootstrap.lsp", $boot, $enc)

Write-Host "Dev mode installed."
Write-Host "Source: $auto\opal-tools  +  $auto\layer-kit"
Write-Host "Restart AutoCAD once. After that: edit a tool, type OLOAD, and the change is live."
